export { createFunction } from './diabolo/create-function'
export { createService } from './diabolo/create-service'
export { lazyCreateServiceImpl } from './diabolo/lazy-create-service-impl'
export { requireService } from './diabolo/require-service'
export { run } from './diabolo/run'
export type { Service } from './diabolo/types/service'
