export { createFunction } from './diabolo/create-function'
export { createService } from './diabolo/create-service'
export { lazyCreateServiceImpl } from './diabolo/lazy-create-service-impl'
export { provide } from './diabolo/provide'
export { requireService } from './diabolo/require-service'
export type { Service } from './diabolo/types/service'
export type { WithServices } from './diabolo/types/with-services'
